### ISSUE TITLE
StimulusJS integration docs incorrectly suggest relative controller path

### ISSUE THREAD

**Issue by xeron** [avo-hq/avodocs#107]
https://docs.avohq.io/2.0/stimulus-integration.html#register-that-controller-with-the-current-stimulus-app

This works in dev with assets fallback but doesn't work in prod with precompiled assets:

```javascript
// app/javascript/avo.custom.js
import SampleController from './controllers/sample_controller'
```

Should be:

```javascript
// app/javascript/avo.custom.js
import SampleController from 'controllers/sample_controller'
```

**Comment by adrianthedev** [comment]
Fixed! Thanks!
