### ISSUE TITLE
Show an example on how to declare variables on resource tools

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avodocs#146]
From [here](https://discord.com/channels/740892036978442260/1184580742894862366).

**Comment by pierry01** [comment]
I have tried to declare the variables in initialize, but I had not success...

**Comment by adrianthedev** [comment]
I added an example [here](https://github.com/avo-hq/main.avodemo.com/commit/c8ecb9b53a770103a993df4c2b3acec0a1faf737).

**Comment by adrianthedev** [comment]
[Docs too](https://github.com/avo-hq/avodocs/commit/88ce1d587640237e168c4520694b1a787cbcc868)
