### ISSUE TITLE
[DUP] Show an example on how to declare variables on resource tools

### ISSUE THREAD

**Issue by pierry01** [avo-hq/avodocs#163]
Adding more details to https://github.com/avo-hq/avodocs/issues/146

```
# frozen_string_literal: true

class CertificateInfo < Avo::BaseResourceTool
  attr_reader :url, :supplier, :company_rf, :certificate

  def initialize(**kwargs)
    super(**kwargs)

    @certificate = @resource.record
    @supplier = @certificate.supplier
    @company_rf = @supplier.company_rf
    @url = Certificates::CalculateLink.call(certificate: @certificate)
  end
end
```

Following the example in the Issue 146, I tried to implement my variables here, but I had no success, because I need access to the record... 

I have tried use resource, `@resource`, record, `@record`, url params, more fields in `kwargs`, anything that can help to find the record, but I failed...

https://docs.avohq.io/3.0/resource-tools.html#where-to-add-logic

I looked here, but I found nothing to help...

**Comment by adrianthedev** [comment]
Version 3.3.3 has https://github.com/avo-hq/avo/pull/2432 that adds the `resource` and `view` to the initializer.
