### ISSUE TITLE
Change all evaluation host entries to execution context

### ISSUE THREAD

**Issue by adrianthedev** [avo-hq/avodocs#97]
In the 3.0 version of the docs we still have many references to `EvaluationHost`, `RecordHost`, and other derivatives.
We need to change all of them to the execution context and link to that.

Also check the `.md` files in the `common` directory.

**Comment by Paul-Bob** [comment]
I think that [this commit](https://github.com/avo-hq/avodocs/pull/96/commits/9112fe963c75441d3e90b5cdf209f6504fb3efff) already solved this issue. I didn't find any `Host` that can be replaced.
